checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "${experiment}/checkpoints"
  filename: "best-{epoch}-{val_acc:.2f}"
  monitor: "val_acc"
  mode: "max"
  save_top_k: 1
  save_last: true
  every_n_epochs: 10

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_acc"
  patience: 10
  mode: "max"
