epochs: 30
batch: 64
imgsz: 224

optimizer:
  name: AdamW
  lr: 3e-5
  weight_decay: 0.03

scheduler:
  name: CosineAnnealingLR
  eta_min: 1e-7

augment:
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  rotation: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2

  flip:
    horizontal: True
    vertical: True
