############
experiment: YOLOv8-2cls-test
mlflow_uri: http://109.248.163.128:5000
store_exp_to: experiments

device: 0
resume: False
debug: False
seed: 42
############

defaults:
  - data: data/data.yaml 

custom_tags: []

model:
  pretrained: yolov8n.pt
  imgsz: 256
  tags: []

hyp: 
  epochs: 200
  batch: 5
  optimizer: AdamW 
  cos_lr: True

  lr0: 0.0015190223860752346
  lrf: 0.09402827811162646
  momentum: 0.7699832015991664
  weight_decay: 0.0007568977500575172
  warmup_epochs: 3.7406242240097027